---
 session_number: 10
 server_ip_range: "10.10.1.0/24"
 client_ip_range: "10.10.2.0/24"
 server_mac: "f8:f2:1e:b2:65:70"
 client_mac: "f8:f2:1e:b2:43:00"
 server_port_start: 80
 server_port_end: 8080
 client_port_start: 9745
 client_port_end: 50214
 rate_bps_start: 30000 #30kbps
 rate_bps_end: 300000 #300kbps
 num_pkts_every_connection: 100
#  packet_length_start: 64
#  packet_length_end: 64
 duration_start: 1 # 30s
 duration_end: 1 # 30s
 flow_size_cdf:
  # - size: 512
  #   probability: 0.2
  # - size: 256
  #   probability: 0.5
  # - size: 128
  #   probability: 0.8
  - size: 64
    probability: 1.0